language: bash

node_js:
    - "9.5"

install:
    - npm install

script:
    - node index.js

deploy:
    provider: pages
    local-dir: platforms
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    verbose: true
    on:
      branch: master
    provider: pages
    target-branch: travis
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    verbose: true
    on:
      branch: master