language: bash

node_js:
    - "9.5"

install:
    - npm install

script:
    - node index.js

deploy:
    provider: pages
    skip-cleanup: true
    target-branch: travis
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master

script:
    - mkdir out
    - tar -cf ./out/platforms.tar -C ./platforms .

deploy:
    provider: pages
    local-dir: out
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    verbose: true
    on:
      branch: master