language: bash

node_js:
    - "9.5"

install:
    - npm install

script:
    - node index.js

deploy:
    - provider: script
      skip_cleanup: true
      script: push.sh
      verbose: true
      on:
        branch: master
    - provider: pages
      skip-cleanup: true
      local-dir: platforms
      github-token: $GITHUB_TOKEN
      keep-history: true
      verbose: true
      on:
        branch: master