language: bash

node_js:
    - "9.5"

install:
    - npm install

script:
    - node index.js
    - mkdir out
    - tar czf ./out/platforms.tar.gz ./platforms

deploy:
    provider: pages
    local-dir: out
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    verbose: true
    on:
      branch: master