language: bash

node_js:
    - "9.5"

install:
    - npm install

script:
    - node index.js
    - mkdir out
    - tar cvzf ./out/platforms.tar.gz -C ./platforms

deploy:
    provider: pages
    skip-cleanup: true
    target-branch: travis
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master